media: assets
content:
  name: posts
  label: Posts
  type: collection
  path: _posts
  fields:
      - { name: title, label: Title, type: string }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: date, label: Date, type: date }
      - { name: comments, label, Comments, type: boolean, default: true }
      - { name: description, label: Description, type: string, options: { maxlength: 160 } }
      
      
      
  